FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["PinguinoApp.API/PinguinoApp.API.csproj", "PinguinoApp.API/"]
RUN dotnet restore "PinguinoApp.API/PinguinoApp.API.csproj"
COPY . .
WORKDIR "/src/PinguinoApp.API"
RUN dotnet build "PinguinoApp.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PinguinoApp.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

CMD ASPNETCORE_URLS="https://*:$PORT" dotnet PinguinoApp.API.dll

RUN useradd -m admin
USER admin
